* D&D Mostly Useless Magical Items

** Mundane Ring:
This ring is of exquisite and ornate workmanship using only the finest gems, gold and platinum. However, a dwemer has been permanently placed upon it so as to make it unimpressive and mundane to anyone who sees it. The owner can, of course, see what it truly is but no one would ever believe them if they told someone else.

** Handkerchief of Useless Skills:
This beautifully colored silk handkerchief, meant to be worn as part of an attire, gives the owner 2d10 additional useless skills. These can include such skills as perfectly singing while standing on one foot in the nude, a flawless recall of historical dates from a completely uninteresting period of history, or even the ability to perform a perfect pirouette on the moon (should they ever get there). The handkerchief will radiate a strong magic and people will understand that the wearer has the ability to do amazing things, but not what they are.

** Decanter of Average Wine:
A beautifully cut crystal decanter with the ability to make any wine taste average - from the most foul rotgut to the finest and most delicate wine, it will always taste like a simple decent house wine.

** Earpieces of Unending Music:
These earpieces (headphones which are comfortable and padded with the softest leather) play a constant stream of music which can also be faintly heard by those around the wearer. It would be a marvel indeed, had the creator not been partial to Muzak. They only ever play Elevator Muzak style of music and nothing can change this.

** Hat of Splendid Fumbling:
This beautiful foppish hat endows the wearer with nearly godlike Charisma (an additional +20). Unfortunately, it also makes them physically inept. The wearer will speak with a lisp, or trip or stumble, laugh at inopportune times with a strange hyena laugh,  or accidentally swipe full glasses off of a table only to have them crashing and spilling on the floor. Additionally, it will make them dribble their food on their front when eating. This all works out to remove any Charisma bonus which the hat confers in the exact same amount (-20) working out to give the wearer exactly as much Charisma as they had when they first put it on.

** Scrolls of Rolling:
These scrolls are usually found blank and can be filled out with any information desired. When the owner steps away, the scrolls will instantly roll back up on their own. This may sound useful, but it can prove to be slightly annoying as they will always do so the moment the owner steps away even for a second, meaning that the endless unscrolling has to be done to get to where they last left off their reading. Also, any objects holding the scrolls open on a table or desk will be violently flipped over as the scrolls roll back up, potentially breaking them.

** Lute of the Apprentice:
This finely and ornately worked and beautifully made lute only has perfect tuning when someone plays it who has no idea how to play a lute. The more talent and skill that person has at playing a lute, the more out of tune it will sound. Unfortunately, as time wears on, a completely new player will slowly learn the craft more and more and, thus, will reach a point when they too will be unable to properly play on the lute.

** Documents of Promised Riches:
These beautifully embossed and signed documents confer upon the owner a vast wealth and riches upon their retirement. These can be the promise of an entire keep, millions of gold pieces, incalculably valuable artwork and more, including entire lands or even a kingdom. If the finder of these documents decides to check their validity, it will be absolutely proven to be real without a doubt - even local rulers will accept the validity of such documents as they literally change and warp reality with a powerful Wish spell.
However, upon each subsequent birthday of the owner, the date of retirement will advance one year, meaning that the person will never actually inherit all of the promise wealth. It will always be lingering in front of them, never to be accessed in their lifetime.

** Gems of the Ordinary:
These are incredibly precious stones, some of them worth upwards of 100,000gp each - however, they all appear to be mundane. People will recognize that they are what they are:
Rubies, Diamonds, Emeralds, Sapphires, etc...but will look unimpressive and they will not want to buy or use them in any way.

** Ninefold Copper:
This unassuming copper piece was created by a starving young mage apprentice. When paying for sundry items or basic necessities, it can assume up to 9 times its worth (meaning up to 9 coppers). This means that a starving student could pay for their meal and beer daily with a single one of these. It can only be used once a day. Once it is used, at dawn, it will reappear in the owner's purse or pouch to be used again. The value can never go up to 10 coppers (the equivalent of a silver piece). For people with a modicum of means, this would be seen as a mostly useless, yet novelty, item.

** Lance of Tilting Windmills:
This powerfully magicked lance, when wielded by a knight on horseback, will actually tilt any windmill and cause it to fall over. There is no dice throw for this to happen and instant contact with any windmill when charged upon a horse will make it topple over sideways. However, this is its only ability as the lance is made of a shoddy and unkempt wood and rusted iron at the tip. If used in combat against any other object or opponent, the lance will either merely break (it is repairable with some nails), or simply be brushed aside like the attack of a mosquito doing no damage whatsoever.

** Armor of the Bulwark:
This full plate set of beautifully made human-sized armor looks fit for a literal king. It is impervious to all attacks - no matter the kind of attack (spells/acid/blows/or anything else physical or even mental) will simply bounce off of the armor as if it had never occurred, leaving no scarring or marks of any kind. However, the person inside cannot move. They can only stand where they donned the armor until someone removes the helmet and are no more useful than a boulder or rock in battle. If someone is inside, they cannot be toppled or pushed over in any way. Not moving includes not being able to swing their arms or lift them in any way. They are able to move their mouth to ask for the helmet to be removed, but no more than that. Should they have the misfortune of donning the armor alone, they may find themselves in a world of trouble. A number of these specialized armors have been discovered with the skeletons of the tragic figures who tried them with no one around to help them. 

** Broom of Melryn the Mage:
This magicked broom is permanently enchanted to sweep up the dwelling of the owner, never stopping and never pausing. It also uses magick to clean the dishes, do the bed sheets, laundry, and any other amount of tidying to make a perfectly spotless tidy home. It often can get in the way of someone walking around their home, but that isn't the worst of it. Melryn was once married to a rather loud and boisterous large woman who would never stop tidying. After her passing, he tried trapping her spirit into the broom and succeeded. Now, the broom not only constantly cleans, but also scolds the owner as if married to them. It will start scolding them at random times, and always when returning home (even if just walking out for a moment and coming back inside). It will start telling them about how they do not appreciate her services, how they are always late for supper, how they should never go out drinking again with their mates, how loudly they snore (especially after drinking), how sloppily they eat, how they should work harder so that it can move out of this hovel (even if it is a literal palace), and more. The broom is indestructable. When found, it will be inert, but will activate the moment it returns home with someone. As it is a beautifully made broom, and many have thought it might thus be a Broom of Flying, this is not uncommon as gilded runes are carved upon the side to convey its magical nature. The broom is not cursed and can freely be dumped or given away.
IF the broom gets very upset, it will turn itself over and start hitting the owner on the head to chase them outside for a while. Flowers may placate the broom for a few hours, but very little else.

** Sundial of Intemporal Time:
This was an early experiment of a mage log ago who tried to stop time. It is a wrist sundial, ornately made and jeweled. His ultimate goal was to be able to stop time, however he failed. It only ever shows the time 14:
00 with the shadow on the dial, even if no sun is present, even in the middle of the darkest dungeon by torchlight, the shadow will not move. The sundial itself is intemporal and cannot change or be destroyed.

** Lockbox of Puzzling:
This very small and ornately carved chest (complete with rounded lid) looks like any other ornately carved puzzle box. However, there is no permanent solution. Inside, there is nothing (even though when shaken, something can be felt and heard moving about). Every time another piece is successfully unlocked, within the box a new piece will magically be created to appear behind the others once they are unlocked as well. Thus, the puzzles never end and the box can never be opened. Even a Wish spell cannot divulge the secrets of the box and, thus, it has confounded even the most powerful and intelligent mages in history who happened upon one.

** Bell of the Simpering Butler:
Another early mage experiment, this simple looking hand bell summons the specter of a magical butler. However, it is a cowardly thing, always simpering and cringing, and refusing to do anything the owner will ever ask out of pure terror and fear. It can converse while it desperately tries to hide behind something (or someone) and whispers back and forth to its owner, but it can never actually accomplish any task. Any show of being irate at this behavior, or shouting, or even slightly raising one's voice, will make the butler run away screaming in terror and vanish. The butler may be summoned again and again, of course, but the result will be the same each and every time. If summoned during battle, it will immediately scream and run away (to disappear) in terror without so much as a word.

** Deck of Common Things:
As one mage tried to duplicate the power of the renown Deck of Many Things, he only was able to create this sub-par stand-in. Each card pulled from the deck will bestow upon the "player" a common household item or farm implement. Thus:
A candle, a plough, a placemat, a clay jar, a trowel. Nothing ever of value is bestowed and any owner generally tends to quickly tire of the game.

** Mug of Grenneth McDraft:
This thick and heavy wooden mug of Dwarven construction is considered to be a failure, if but a valiant attempt. The mug originally was meant to be never-ending with a supply of tasty beer. However, the mug only ever produces about a thimble full every hour or so. If not emptied, the mug will not produce more until it is emptied by drinking or spilling out. However, it is unending and storing this in their pack will potentially (if not stored upright at all times) cause it to continually drip beer at the bottom and, eventually, make them smell like beer gone bad and mildew. Most Dwarves, when realizing what this mug does, enter into a slight temporary state of depression.

** Jug of Soured Milk:
This simple looking clay jug can be filled with water. The water when poured out, will be slightly soured milk. It is completely useless apart from some cooking uses.

** Gloves of the Glib Pickpocket:
These finely crafted supple leather gloves make it a certainty (100%) that any pickpocketing attempt will fail. They will, however, allow the wearer to talk themselves out of the situation (100%) and even retain the object. However, the moment the gloves are removed, the victim will remember everything and will seek out the thief for the rest of their life, no matter how small the object or amount stolen. If any guards were present during the talking effect, the thief will become a prime wanted criminal in the entire land.
If the attempt is made upon enemies in an enemy location, the wearer of the gloves will be able to talk themselves out of being punished for pickpocketing, but it will not enable them to talk themselves out of being there in the first place. Thus, treat any attempt at pickpocketing bandits or other enemies as a normal enemy encounter.

** Brooch of Chiming:
A lovely ornate gold and silver brooch of a cuckoo bird. When worn upon one's vest or shirt, it will pleasantly chime each hour of the day with a little chime. However, there is no way to silence the brooch and, thus, may be deadly in certain situations, or considered rude in others (say at a funeral or play or concert).

** Statuette of the Cow:
This lovely little marble statuette (small enough to fit in one's pocket) can, upon placing on the ground and using a command word, turn into a cow. The cow has no interest in anything around it other than eating whatever grass or hay may be nearby, and will last for a full hour. If the cow is killed, it will return to the form of the statuette and able to be summoned again the next day. The cow also produces no milk as it is in a permanent state of having just been milked an hour before.

** Quill of Cantankerous Copying:
This magicked quill enables the owner to copy anything down that is set next to the quill. Even entire volumes of books can be set upon a table with the quill and the quill will copy them faithfully to the letter within an hour. Unfortunately, the quill suffers from Tourette Syndrome. Thus, every two or three sentences, a sentence or two, or even a paragraph, of insulting screed will emerge as if from an unhinged and insulting maniac. This renders the copies much longer than their originals, and also very taxing to fully read. The quill will also shout out every single insult as it writes it down, making it impossible to use in any library without being thrown out and banned forever.

** Robes of the Archmagi's Assistant:
These beautifully made silk wizard robes are a sight to behold:
blazing with colours ad different designs. They were made for an Archmage's Assistant. Thus, they only confer mundane powers, such as being an extremely good book keeper, manager of someone else's business and operations, time keeper, organizer, etc... No actual wizard powers are enhanced by these robes in any way whatsoever. They would be the perfect gift for an assistant.

** Bracelet of Humming Power:
This wide, beaten platinum with gold edges, bracelet will lightly vibrate and hum softly anytime it is near (30') a magical item - including itself. There is no way to turn it off.

** Letter Opener of Swiftness:
This smooth-edged minimalist letter opener has one single purpose:
It will open letters in one swift motion of the wrist, flawlessly, each and every time. Useless to most people, but a very useful item for some bureaucrats or people involved in a lot of correspondence.

** Signet of Sealing:
This simple looking gold ring will adapt it's signet on the front to any symbol the owner has in his or her family. Once the symbol is chosen, it cannot be changed unless the seal itself is changed through official channels - thus preventing imposter signet activity. Furthermore, when pressed against paper, it will instantly leak a sufficient quantity of sealing wax in any colour desired, so as to seal the document, meaning that no wax is necessary on its own for the action. It will leave a perfect seal every time. Should someone acquire this ring who has no title or family crest, they may opt to create one in their mind as long as it does not conflict with any other officially registered ones or portray them as anything but a commoner, until such time as they are elevated above their status.

** Wig and Dress of the Marquise of Trantor:
This beautiful wig and dress set was once made for the renown Marquise of Trantor - an effete snob of the highest order. Her goal was to create a party ensemble which could never, under any circumstances, be undone. When found, it will look like a very elegant dress and elaborate wig, but nothing exceptional. However, upon donning the outfit and going to a party, the dress will instasntly change to be the most ravishingly expensive and ostentatious dress in the entire party, no matter what form that may take. The wig will also change to an appropriately taller stature, complete with accessories such as moving windmills, boats with sparklers, magically circling balls, a clock, or any other outrageously silly additions that high nobility could add to try to outdo one another in showmanship.
Unfortunately, some royals do not like being outdone and, thus, the Marquise (and her husband) met their untimely end after outdoing and offending the royal couple upon a particularly sour night.
The ensemble also comes with a matching wig and outfit for a man (which belonged to her husband).
There is literally no outfit at any party which will not be outdone by these ensembles, so the wearer is going to have to take care not to wind up in the same situation as the previous owners and creators.
*Note:* These are all based upon extremely elaborate illusions which only the highest magic can ever reveal. But no matter how many enormous diamonds, pearls, emeralds, silk brocades, or any other frippery is presented, none can ever be sold off for actual money.
Also: The ensemble and wigs can work seperately or together. One may simply wear the ensemble, or just the wig. There is no command given and the true form is only ever revealed at home in the bedroom while taking it off or putting it on. After that, it will always ostentatiously outshine anyone around it, no matter the circumstance.

* Not entirely useless items:

** Toiletry Kit of Calipro the Clean:
This very small soft leather pouch is not entirely useless and can be highly prized by travelers. Taking only the amount of space of a small playing card, it can be unfolded into a 10' X 10' leather swatch on the ground. Standing on the swatch will immediately pull up "curtains" of soft leather around the entire space and seal the occupant off from prying eyes. Inside will be a full working privy with flushing water as well as new toilet paper, a sink with hot and cold water, a mirror, a bathtub and shower with hot and cold water, a towel rack with warmed and dry, thick and soft, towels, a full fresh shaving/trimming kit, fresh toothbrush with toothpaste, new soaps in a variety of scents, bubble bath, a fresh natural sponge, a variety of shampoos, and other morning care accessories (for women as well). The items are refreshed only once a day, so that if someone were to use the kit more than once a day, they will have to make use of what they already started with. But there are enough provisions to last a few people throughout the day through several uses each. A small magical grill set near the mirror will also play soft soothing music at will.
Once finished, the person merely has to exit one of the sides of the room and the entire thing will collapse back down to size.
No additional items may be placed within the space other than the ones provided. If they are, they are simply left upon the ground when it collapses back down. However, there is one exception to this rule:
Clothes.
The owner may place dirty clothes into the hamper and, the next morning, they will be returned fresh, clean, pressed and folded as if newly laundered. Only one full set of clothing may be dealt with in this manner (one pair of socks, underwear, shirt, hose/pants, shoes, vest, jacket, etc...). If more than one full outfit is placed in the hamper, the extra one will be left upon the ground when collapsing back down, just like any other added item.
Toiletry items also included are:
mouthwash, floss, blunted small scissors for trimming, baby powder, aftershave/cologne or perfume, q-tips, makeup of various shades and types, hairpins, etc...anything a person of means would have in their bathroom.
Also included is a small dish of curiously strong cinnamon mints under the mirror.
The entire area is also well ventilated so that if a continuinng file of people are to use the facilities, it will not be belabored by the smells of the previous user. It also is comfortably warm, providing protection from the harshest weather conditions on the outside.

*Note:*
If anyone tries to peer inside the space while another is in it, all they will see is an unlit (black) empty space, thus ensuring privacy from prying eyes.
Calipro has been known to make other travel gear of this nature (such as a sleeping tent and kitchen/living room ) and each one is highly prized and sought after.

